version: '3'
services:
  app:
    build: ./docker/app
    image: bizdire:yii2
    restart: 'no'
    ports:
      - '${APP_PORT}:80'
    volumes:
      - './:/var/www'
      - './docker/php/php.ini:/etc/php/8.1/apache2/php.ini'
      - './docker/php/php.ini:/etc/php/8.1/cli/php.ini'
    links:
      - mariadb
      - adminer
  mariadb:
    image: 'mariadb:10.3.28'
    restart: 'no'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: '${DB_DATABASE}'
  adminer:
    image: adminer:latest
    restart: 'no'
    links:
      - mariadb
    ports:
      - '${ADM_PORT}:8080'